export const NotificationType = {
	COMMENT: 'COMMENT',
	LIKE: 'LIKE',
	FOLLOW: 'FOLLOW',
	POST: 'POST',
	REPLYCOMMENT: 'REPLYCOMMENT',
	LIKECOMMENT: 'LIKECOMMENT',
	WARNINGPOST: 'WARNINGPOST',
  WARNINGCOMMENT: 'WARNINGCOMMENT',
  BLOCK_POST: 'BLOCK_POST',
};

export const REPORT_REASON = {
	SPAM: 'SPAM',
	VIOLENCE: 'VIOLENCE',
	HARASSMENT: 'HARASSMENT',
};
